import { Injectable } from '@angular/core';
import { io } from 'socket.io-client';
import { localUrl } from '@env/environment';
import { TokenStoreService } from '../store/common-store/token-store.service';
@Injectable({
  providedIn: 'root'
})
export class SocketService {

  private socket = io(localUrl, {
    auth: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIxZmU1M2MyNmQ0MDI0ZGQzMTI0MzciLCJyb2wiOiJkZWZhdWx0OmRhc2hib2FyZCxkZWZhdWx0OmRhc2hib2FyZDphbmFseXNpcyxkZWZhdWx0OnBhZ2UtZGVtbyxkZWZhdWx0OnBhZ2UtZGVtbzpyZXN1bHQsZGVmYXVsdDpwYWdlLWRlbW86cmVzdWx0OnN1Y2Nlc3MsZGVmYXVsdDpwYWdlLWRlbW86cmVzdWx0OmZhaWwsZGVmYXVsdDpwYWdlLWRlbW86ZXhjZXB0LGRlZmF1bHQ6cGFnZS1kZW1vOmV4Y2VwdDpleGNlcHQ0MDMsZGVmYXVsdDpwYWdlLWRlbW86ZXhjZXB0OmV4Y2VwdDQwNCxkZWZhdWx0OnBhZ2UtZGVtbzpleGNlcHQ6ZXhjZXB0NTAwLGRlZmF1bHQ6cGFnZS1kZW1vOmV4Y2VwdDpuZXR3b3JrLWVycm9yLGRlZmF1bHQ6cGFnZS1kZW1vOmV4Y2VwdDpuby1kYXRhLGRlZmF1bHQ6cGFnZS1kZW1vOnBlcnNvbmFsLGRlZmF1bHQ6cGFnZS1kZW1vOnBlcnNvbmFsOnBlcnNvbmFsLWNlbnRlcixkZWZhdWx0OnBhZ2UtZGVtbzpwZXJzb25hbDpwZXJzb25hbC1zZXR0aW5nLGRlZmF1bHQ6cHJvZHVjdCxkZWZhdWx0OnByb2R1Y3Q6c2VhcmNoLGRlZmF1bHQ6cHJvZHVjdDpuZXdwcm9kdWN0LGRlZmF1bHQ6cHJvZHVjdDpjYXRlZ29yeSxkZWZhdWx0OnN5c3RlbSxkZWZhdWx0OnN5c3RlbTphY2NvdW50LGRlZmF1bHQ6c3lzdGVtOmFjY291bnQ6YWRkLGRlZmF1bHQ6c3lzdGVtOmFjY291bnQ6ZWRpdCxkZWZhdWx0OnN5c3RlbTpyb2xlLW1hbmFnZXIsZGVmYXVsdDpzeXN0ZW06cm9sZS1tYW5hZ2VyOmFkZCxkZWZhdWx0OnN5c3RlbTpyb2xlLW1hbmFnZXI6ZWRpdCxkZWZhdWx0OnN5c3RlbTpyb2xlLW1hbmFnZXI6ZGVsLGRlZmF1bHQ6c3lzdGVtOnJvbGUtbWFuYWdlcjpzZXQtcm9sZSxkZWZhdWx0OnN5c3RlbTptZW51LGRlZmF1bHQ6c3lzdGVtOm1lbnU6YWRkLGRlZmF1bHQ6c3lzdGVtOm1lbnU6ZWRpdCxkZWZhdWx0OnN5c3RlbTptZW51OmRlbCxkZWZhdWx0OnN5c3RlbTptZW51OmFkZGxvd2xldmVsLGRlZmF1bHQ6c3lzdGVtOmRlcHQsZGVmYXVsdDpzeXN0ZW06ZGVwdDphZGQsZGVmYXVsdDpzeXN0ZW06ZGVwdDplZGl0LGRlZmF1bHQ6c3lzdGVtOmRlcHQ6ZGVsLGRlZmF1bHQ6c3lzdGVtOmRlcHQ6YWRkbG93bGV2ZWwsZGVmYXVsdDpzeXN0ZW06ZGF0YXNjLGRlZmF1bHQ6c3lzdGVtOmRhdGFzYzphZGQsZGVmYXVsdDpzeXN0ZW06ZGF0YXNjOmVkaXQsZGVmYXVsdDpzeXN0ZW06ZGF0YXNjOmRlbCxkZWZhdWx0OnN5c3RlbTpodW9uZ2RhbixkZWZhdWx0OnN5c3RlbTpodW9uZ2RhbjphZGQsZGVmYXVsdDpzeXN0ZW06aHVvbmdkYW46YWxsRGVsLGRlZmF1bHQ6c3lzdGVtOmh1b25nZGFuOnVwZGF0ZSxkZWZhdWx0OmFib3V0IiwidXNlcm5hbWUiOiJOYW0gUGjhuqFtIiwiZW1haWwiOiJuYW1hbmRyb2lkLml0QGdtYWlsLmNvbSIsImlhdCI6MTY5MzM3ODk4NywiZXhwIjoxNjkzNDY1Mzg3fQ.M9aPJw-CAnUUDoG3DFFnXsi7IBcbHy69_LNcSvbAjQ4'
    }
  });

  constructor(private tokenStoreService: TokenStoreService) { }

  on(eventName: string, callback: any) {
    this.socket.on(eventName, callback);
  }

  emit(eventName: string, data: any) {
    this.socket.emit(eventName, data);
  }
}
